services:
  db:
    image: postgres:16.4
    container_name: fast-api-boilerplate
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: fast-api-boilerplate
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: fast-api-boilerplate
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
